spring:
  datasource:
    hikari:
      maximum-pool-size: 2
database:
  username: root
  password: root
  host: localhost
  port: 3306

  dbname: attendence_cx
logging:
  config: classpath:log4j2-dev.yml
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
