spring:
  datasource:
    hikari:
      maximum-pool-size: 2
database:
  username: testdbadmin
  password: Jxzj@1688
  host: 60.205.186.121
  port: 12307
  dbname: trade_engine
logging:
  config: classpath:log4j2-test.yml
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
