spring:
  datasource:
    hikari:
      maximum-pool-size: 2
database:
  username: root
  password: root
  host: localhost
  port: 3306

#database:
#  username: root
#  password: Jxzj@1688
#  host: 172.16.1.88
#  port: 3306
  
  dbname: dubbo_engine
logging:
  config: classpath:log4j2-dev.yml
dubbo:
  registry:
    address: zookeeper://127.0.0.1:2181
